basic.showIcon(IconNames.Heart)
basic.pause(1000)
maqueen.motorRun(maqueen.Motors.All, maqueen.Dir.CW, 255)
basic.pause(2000)
maqueen.motorStop(maqueen.Motors.All)
basic.pause(1000)
maqueen.motorRun(maqueen.Motors.All, maqueen.Dir.CCW, 255)
basic.pause(2000)
maqueen.motorStop(maqueen.Motors.All)
basic.pause(1000)
maqueen.motorRun(maqueen.Motors.M2, maqueen.Dir.CW, 100)
music.playTone(330, music.beat(BeatFraction.Whole))
basic.pause(1000)
maqueen.motorStop(maqueen.Motors.All)
basic.pause(1000)
maqueen.motorRun(maqueen.Motors.M1, maqueen.Dir.CW, 100)
music.playTone(392, music.beat(BeatFraction.Whole))
basic.pause(1000)
maqueen.motorStop(maqueen.Motors.All)
basic.pause(1000)
basic.forever(function () {
	
})
